// <auto-generated />
using System;
using KaleContentOps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaleContentOps.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KaleContentOps.Models.ContentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorNickname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatorOpenId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatorUsername")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("PicId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductionMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VideoPostTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("PicId");

                    b.HasIndex("ProductionMethodId");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("ContentLogs");
                });

            modelBuilder.Entity("KaleContentOps.Models.ContentMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AverageWatch")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Comments")
                        .HasColumnType("bigint");

                    b.Property<long>("ContentLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("DemographicsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FullWatchRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Likes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MetricEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MetricStartDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("NewFollowers")
                        .HasColumnType("bigint");

                    b.Property<long?>("Reach")
                        .HasColumnType("bigint");

                    b.Property<long?>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long?>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContentLogId");

                    b.ToTable("ContentMetrics");
                });

            modelBuilder.Entity("KaleContentOps.Models.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KK",
                            Color = "yellow",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Keranjang Kuning",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "NON_KK",
                            Color = "blue",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Non-KK",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Code = "AUTO_GMV_LIVE",
                            Color = "purple",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Auto GMV Live",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KaleContentOps.Models.MasterPic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterPics");
                });

            modelBuilder.Entity("KaleContentOps.Models.ProductionMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductionMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SELF_PRODUCE",
                            IsActive = true,
                            Name = "Self Produce"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AI_PRODUCE",
                            IsActive = true,
                            Name = "AI Produce"
                        });
                });

            modelBuilder.Entity("KaleContentOps.Models.ContentLog", b =>
                {
                    b.HasOne("KaleContentOps.Models.ContentType", "ContentType")
                        .WithMany("ContentLogs")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KaleContentOps.Models.MasterPic", "Pic")
                        .WithMany("ContentLogs")
                        .HasForeignKey("PicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KaleContentOps.Models.ProductionMethod", "ProductionMethod")
                        .WithMany("ContentLogs")
                        .HasForeignKey("ProductionMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContentType");

                    b.Navigation("Pic");

                    b.Navigation("ProductionMethod");
                });

            modelBuilder.Entity("KaleContentOps.Models.ContentMetric", b =>
                {
                    b.HasOne("KaleContentOps.Models.ContentLog", "ContentLog")
                        .WithMany("Metrics")
                        .HasForeignKey("ContentLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentLog");
                });

            modelBuilder.Entity("KaleContentOps.Models.ContentLog", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("KaleContentOps.Models.ContentType", b =>
                {
                    b.Navigation("ContentLogs");
                });

            modelBuilder.Entity("KaleContentOps.Models.MasterPic", b =>
                {
                    b.Navigation("ContentLogs");
                });

            modelBuilder.Entity("KaleContentOps.Models.ProductionMethod", b =>
                {
                    b.Navigation("ContentLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
